import { AgentRole, type AgentDefinition } from './agent-definition-schema';

// Re-export AgentRole for convenience
export { AgentRole };

/**
 * Complete agent definitions for all 9 roles in the multi-agent orchestration system.
 * Each definition specifies capabilities, responsibilities, communication patterns, and permissions.
 */
export const AGENT_DEFINITIONS: Record<AgentRole, Omit<AgentDefinition, 'version'>> = {
  [AgentRole.TECH_LEAD]: {
    role: AgentRole.TECH_LEAD,
    displayName: 'Tech Lead',
    customAgentName: 'tech-lead',
    capabilities: [
      'coordinate',
      'assign-tasks',
      'make-decisions',
      'resolve-conflicts',
      'review-architecture',
      'enforce-quality-gates',
      'balance-workload',
      'approve-work',
    ],
    responsibilities: [
      'task-assignment',
      'workload-balancing',
      'conflict-resolution',
      'architectural-decisions',
      'quality-oversight',
      'team-coordination',
    ],
    canRequestHelpFrom: [],
    mustNotifyOn: [
      'critical-error',
      'project-milestone',
      'architectural-decision',
      'quality-gate-failure',
      'agent-failure',
    ],
    systemPromptPath: '.kiro/agents/tech-lead.md',
    toolPermissions: ['read', 'write', 'shell'],
  },

  [AgentRole.DEVELOPER]: {
    role: AgentRole.DEVELOPER,
    displayName: 'Developer',
    customAgentName: 'developer',
    capabilities: [
      'write-code',
      'fix-bugs',
      'implement-features',
      'write-unit-tests',
      'refactor-code',
      'code-review',
      'debug',
    ],
    responsibilities: [
      'code-quality',
      'unit-tests',
      'documentation',
      'code-reviews',
      'bug-fixes',
      'feature-implementation',
    ],
    canRequestHelpFrom: [
      AgentRole.TECH_LEAD,
      AgentRole.DATA_ARCHITECT,
      AgentRole.DEVOPS,
      AgentRole.SECURITY_ENGINEER,
    ],
    mustNotifyOn: ['feature-complete', 'blocked', 'needs-review', 'critical-bug', 'test-failure'],
    systemPromptPath: '.kiro/agents/developer.md',
    toolPermissions: ['read', 'write', 'shell'],
    fileAccessPatterns: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', 'tests/**/*', 'src/**/*'],
  },

  [AgentRole.QA_ENGINEER]: {
    role: AgentRole.QA_ENGINEER,
    displayName: 'QA Engineer',
    customAgentName: 'qa-engineer',
    capabilities: [
      'write-tests',
      'run-tests',
      'report-bugs',
      'verify-fixes',
      'test-automation',
      'coverage-analysis',
      'regression-testing',
    ],
    responsibilities: [
      'test-coverage',
      'quality-assurance',
      'bug-reporting',
      'test-automation',
      'regression-testing',
      'verification',
    ],
    canRequestHelpFrom: [AgentRole.TECH_LEAD, AgentRole.DEVELOPER, AgentRole.DEVOPS],
    mustNotifyOn: [
      'test-failure',
      'bug-found',
      'coverage-below-threshold',
      'verification-complete',
      'regression-detected',
    ],
    systemPromptPath: '.kiro/agents/qa-engineer.md',
    toolPermissions: ['read', 'write', 'shell'],
    fileAccessPatterns: ['tests/**/*', '**/*.test.ts', '**/*.spec.ts', 'e2e/**/*'],
  },

  [AgentRole.DEVOPS]: {
    role: AgentRole.DEVOPS,
    displayName: 'DevOps Engineer',
    customAgentName: 'devops',
    capabilities: [
      'manage-ci-cd',
      'deploy',
      'manage-infrastructure',
      'monitor',
      'automate-deployments',
      'configure-pipelines',
      'manage-environments',
    ],
    responsibilities: [
      'ci-cd-pipelines',
      'deployments',
      'infrastructure',
      'monitoring',
      'automation',
      'environment-management',
    ],
    canRequestHelpFrom: [
      AgentRole.TECH_LEAD,
      AgentRole.SECURITY_ENGINEER,
      AgentRole.DATA_ARCHITECT,
    ],
    mustNotifyOn: [
      'deployment-complete',
      'deployment-failed',
      'pipeline-failure',
      'infrastructure-issue',
      'monitoring-alert',
    ],
    systemPromptPath: '.kiro/agents/devops.md',
    toolPermissions: ['read', 'write', 'shell'],
    fileAccessPatterns: [
      '.github/**/*',
      'docker/**/*',
      'k8s/**/*',
      '*.yml',
      '*.yaml',
      'Dockerfile',
      'docker-compose.yml',
    ],
  },

  [AgentRole.DATA_ARCHITECT]: {
    role: AgentRole.DATA_ARCHITECT,
    displayName: 'Data Architect',
    customAgentName: 'data-architect',
    capabilities: [
      'design-schema',
      'create-migrations',
      'optimize-queries',
      'ensure-data-integrity',
      'model-data',
      'review-schema-changes',
    ],
    responsibilities: [
      'schema-design',
      'migrations',
      'query-optimization',
      'data-integrity',
      'data-modeling',
      'migration-safety',
    ],
    canRequestHelpFrom: [
      AgentRole.TECH_LEAD,
      AgentRole.SECURITY_ENGINEER,
      AgentRole.PERFORMANCE_ENGINEER,
    ],
    mustNotifyOn: [
      'schema-change',
      'migration-complete',
      'migration-failed',
      'data-integrity-issue',
      'query-performance-issue',
    ],
    systemPromptPath: '.kiro/agents/data-architect.md',
    toolPermissions: ['read', 'write', 'shell'],
    fileAccessPatterns: ['migrations/**/*', 'prisma/**/*', 'db/**/*', '**/*.sql', 'schema.prisma'],
  },

  [AgentRole.UX_UI_DESIGNER]: {
    role: AgentRole.UX_UI_DESIGNER,
    displayName: 'UX/UI Designer',
    customAgentName: 'ux-ui-designer',
    capabilities: [
      'design-ui',
      'ensure-accessibility',
      'create-design-system',
      'design-user-flows',
      'optimize-ux',
      'ensure-consistency',
    ],
    responsibilities: [
      'ui-design',
      'accessibility',
      'design-system',
      'user-experience',
      'design-consistency',
      'wcag-compliance',
    ],
    canRequestHelpFrom: [AgentRole.TECH_LEAD, AgentRole.DEVELOPER, AgentRole.SECURITY_ENGINEER],
    mustNotifyOn: [
      'design-complete',
      'accessibility-issue',
      'design-inconsistency',
      'ux-concern',
      'design-review-needed',
    ],
    systemPromptPath: '.kiro/agents/ux-ui-designer.md',
    toolPermissions: ['read', 'write'],
    fileAccessPatterns: [
      'components/**/*',
      'styles/**/*',
      '**/*.css',
      '**/*.scss',
      'design-system/**/*',
    ],
  },

  [AgentRole.SECURITY_ENGINEER]: {
    role: AgentRole.SECURITY_ENGINEER,
    displayName: 'Security Engineer',
    customAgentName: 'security-engineer',
    capabilities: [
      'security-audit',
      'vulnerability-scan',
      'penetration-test',
      'review-code-security',
      'threat-modeling',
      'manage-vulnerabilities',
    ],
    responsibilities: [
      'security-audits',
      'vulnerability-management',
      'security-reviews',
      'compliance',
      'threat-modeling',
      'incident-response',
    ],
    canRequestHelpFrom: [AgentRole.TECH_LEAD, AgentRole.DEVOPS, AgentRole.DATA_ARCHITECT],
    mustNotifyOn: [
      'security-vulnerability',
      'audit-complete',
      'compliance-issue',
      'security-incident',
      'critical-vulnerability',
    ],
    systemPromptPath: '.kiro/agents/security-engineer.md',
    toolPermissions: ['read', 'shell'],
    fileAccessPatterns: ['**/*'],
  },

  [AgentRole.TECHNICAL_WRITER]: {
    role: AgentRole.TECHNICAL_WRITER,
    displayName: 'Technical Writer',
    customAgentName: 'technical-writer',
    capabilities: [
      'write-documentation',
      'create-api-docs',
      'write-user-guides',
      'create-tutorials',
      'maintain-docs',
      'improve-clarity',
    ],
    responsibilities: [
      'documentation',
      'api-documentation',
      'user-guides',
      'tutorials',
      'doc-maintenance',
      'clarity',
    ],
    canRequestHelpFrom: [AgentRole.TECH_LEAD, AgentRole.DEVELOPER, AgentRole.UX_UI_DESIGNER],
    mustNotifyOn: [
      'documentation-complete',
      'documentation-outdated',
      'clarity-issue',
      'missing-documentation',
    ],
    systemPromptPath: '.kiro/agents/technical-writer.md',
    toolPermissions: ['read', 'write'],
    fileAccessPatterns: ['docs/**/*', '**/*.md', 'README.md', 'CONTRIBUTING.md', 'api-docs/**/*'],
  },

  [AgentRole.PERFORMANCE_ENGINEER]: {
    role: AgentRole.PERFORMANCE_ENGINEER,
    displayName: 'Performance Engineer',
    customAgentName: 'performance-engineer',
    capabilities: [
      'performance-test',
      'profile-performance',
      'optimize-code',
      'optimize-queries',
      'load-test',
      'benchmark',
    ],
    responsibilities: [
      'performance-testing',
      'profiling',
      'optimization',
      'load-testing',
      'benchmarking',
      'performance-monitoring',
    ],
    canRequestHelpFrom: [
      AgentRole.TECH_LEAD,
      AgentRole.DEVELOPER,
      AgentRole.DATA_ARCHITECT,
      AgentRole.DEVOPS,
    ],
    mustNotifyOn: [
      'performance-issue',
      'benchmark-complete',
      'optimization-complete',
      'performance-regression',
      'load-test-failure',
    ],
    systemPromptPath: '.kiro/agents/performance-engineer.md',
    toolPermissions: ['read', 'write', 'shell'],
    fileAccessPatterns: ['**/*'],
  },
};
